
        <div class="copyright"><?php  echo $this->getCopyright();?></div>
        <div id="payment-methods">
            <ul>
                <li><a class="paypal" href="1">&nbsp;</a></li>
                <li><a class="visa" href="2">&nbsp;</a></li>
                <li><a class="mastercard" href="3">&nbsp;</a></li>
                <li><a class="discover" href="4">&nbsp;</a></li>
            </ul>
        </div>

