<?php
/**
 * Created by PhpStorm.
 * User: XUANTUNG
 * Date: 13/04/2017
 * Time: 15:21
 */

class Tungdx_Feedbacks_Block_Adminhtml_Feedback_Grid extends Mage_Adminhtml_Block_Widget_Grid {

    protected function _prepareCollection() {
        $collection = Mage::getResoureModel('tungdx_feedbacks/feedback_collection');
        $this->setCollection($collection);
        return parent ::_prepareCollection(); // TODO: Change the autogenerated stub
    }

    protected function _prepareColumns() {
        $this->addColumn('feedback_id', array(
            'header' => $this->_getHelper('Feedback ID'),
            'type'   => 'number',
            'index'  => 'feedback_id'
        ));
        $this->addColumn('customer_name', array(
            'header' => $this->_getHelper('Customer Name'),
            'type'   => 'text',
            'index'  => 'customer_name'
        ));
        $this->addColumn('customer_email', array(
            'header' => $this->_getHelper('Customer Email'),
            'type'   => 'text',
            'index'  => 'customer_email'
        ));
        $this->addColumn('customer_feedback', array(
            'header' => $this->_getHelper('Customer Feedback'),
            'type'   => 'text',
            'index'  => 'customer_feedback'
        ));
        return parent ::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    protected function _getHelper() {
        return Mage::helper('tungdx_feedbacks');
    }
}